services:
  bnb-monitor:
    build: .
    environment:
      TELEGRAM_BOT_TOKEN: "12582xxxx68:AAGMtdEyycnH065TOWxxxxxV0imL07h2io"
      TELEGRAM_CHAT_ID: "-1xxx317933333"
      BSC_WALLET_ADDRESSES: "0x775486574864865aefeafgwedgssdg,0x987at5sfa7d6frb7a6bfdv7aebfvdi7sv"
      BSC_RPC_URL: "https://igogog.go/api/v1/8s7t8vstnfv8e"
      CHECK_INTERVAL: "60000" #1 minute
      BLOCK_BUFFER: "12"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.2'
          memory: 64M
